
import { Inter } from "next/font/google";
import "./globals.css"
import { Provider } from "react-redux";
import Navbar from "./component/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by Create Next app",
};

export default function RootLayout({
  children}) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
          
          <Navbar />
          
          {children}
        
        </Provider>
      
      </body>
    </html>
  );
}